### ISSUE TITLE
expose an option to turn off adding css classes to the html element

### ISSUE THREAD

**Issue by albell** [typekit/webfontloader#120]
With very large numbers of fonts loaded, they're DOM clutter.

**Comment by adamschwartz** [comment]
@bramstein I see that the option was added in 771c5088fc8d4ae5738bf8c5776d2186753059d6, however, I’m still seeing the classes added. Here’s my code:

```jade
    script(src="//ajax.googleapis.com/ajax/libs/webfont/1.5.10/webfont.js")
    script.
      WebFont.load({
        typekit: { id: 'xxxxxx' },
        classes: false
      })
```

Am I doing something wrong?

_A possibly related question:_ From the looks of it, the `classes` boolean is passed through to the internal `Typekit.load` call. Does this mean that this option would work with the standard Typekit embed as well?

```jade
mixin typekit
  script(src="//use.typekit.net/xxxxxxx.js")
  script.
    try{Typekit.load({classes:false});}catch(e){}
```

If so, does this mean that a Kit would need to be republished for this to propagate through? (I tried this to no avail as well unfortunately.)

**Comment by bramstein** [comment]
@adamschwartz Hm, that looks like a bug. It works for the custom module, but not for Typekit. I'll look into it.

The Typekit JavaScript also supports the `classes` and `events` parameters, and that works with a standalone kit (though it seems it is broken when loading a kit through WFL).

**Comment by adamschwartz** [comment]
@bramstein not sure I’m following.

> The Typekit JavaScript also supports the `classes` and `events` parameters, and that works with a standalone kit (though it seems it is broken when loading a kit through WFL).

The Kit ID we use on https://eager.io (`gwr5cpo`) still adds classes when loaded in this format:

```jade
script(src="//use.typekit.net/xxxxxxx.js")
script.
  try{Typekit.load({classes:false});}catch(e){}
```

Isn’t that a “standalone” kit not loaded through WFL?

If you’re saying that “it works for the custom module”, my guess is the bug here lies solely within Typekit, since in both of my tests (the examples of my previous comment, but with `gwr5cpo` instead of `xxx...`), the resulting font was the same Typekit font (whether loaded via `WebFont.load` or `Typekit.load`). If this is the case, perhaps I should contact `support@typekit.com` instead?

**Comment by bramstein** [comment]
@adamschwartz It should work with standalone kits provided the Web Font Loader is not on the page. There is definitely a bug in the Typekit JavaScript when loaded through the Web Font Loader, I'm looking into fixing this.

**Comment by adamschwartz** [comment]
Interesting, that may have been the issue (just having the presence of the Web Font Loader on the page). It looks like the issue I had with the standalone kit has resolved itself. Thanks! Good luck with the Web Font loader issue.

**Comment by pugsley** [comment]
*bump* be great to get this fixed!

**Comment by atran** [comment]
bump
