### ISSUE TITLE
unable to make multiple typekit requests

### ISSUE THREAD

**Issue by jedierikb** [typekit/webfontloader#152]
In an app we are building, we use webfontloader to load in one typekit-id (with just one font) for a 'preloader' screen, and then, still on the same page, we use a different typekit-id to load in many more fonts for the full web application.

However... the second typekit-id does not seem to be working.  In fact... no callbacks happen at all.  We have tested both typekit-ids separately, and both work.  Is there a technical reason I cannot use webfontloader a second time to load more fonts with another typekit-id?

Both requests are made using this template:

```javascript
WebFont.load({
    typekit: {
        id: 'xxxxx'
    },
    active: function() {
        console.log("active");
    },
    inactive: function() {
        console.log("inactive");
    }
});
```

related:
http://help.typekit.com/customer/portal/articles/978705-using-multiple-kits-on-your-site

**Comment by bramstein** [comment]
Sorry for the delay on this. It required some big changes in our kit JavaScript. Those have been made now, and loading multiple kits through the Web Font Loader should now work. Let me know if it doesn't.

**Comment by samstoller** [comment]
Works for me. Thanks!

**Comment by bramstein** [comment]
Excellent. I'm closing this issue for now, but feel free to re-open it if someone is still experiencing problems.

**Comment by jedierikb** [comment]
works great, much thanks
