### ISSUE TITLE
Standard Font Load Events support

### ISSUE THREAD

**Issue by paulirish** [typekit/webfontloader#179]
If a browser supports proper font load events, the implementation in the webfontloader can be massively simplified. I'd love to see this library support the native primitives. 

Blink is looking to ship font load events in the near future: https://groups.google.com/a/chromium.org/d/msg/blink-dev/kWkdUACnPn4/G_ZLiuQcwFoJ

**Comment by bramstein** [comment]
Closing this issue, as this will ship soon (see #262).
