### ISSUE TITLE
Text parameter is not returning appropriately smaller font files

### ISSUE THREAD

**Issue by gavinsmith** [typekit/webfontloader#183]
```
WebFont.load({
  google: {
    families: ['Droid Sans'],
    text: { 'Droid Sans': 'Droid Sans' }
  }
});
```

This should load roughly the same file referenced by this CSS file, according to my understanding ([this PR](https://github.com/typekit/webfontloader/pull/75) added the functionality):
http://fonts.googleapis.com/css?family=Droid+Sans&text=Droid%20Sans

That .woff file is ~1.8KB. Instead, webfont loader configured as above returns this:

http://themes.googleusercontent.com/static/fonts/droidsans/v4/s-BiyweUPV0v-yRb-cjciL3hpw3pgy2gAi-Ip7WPMi0.woff

It's 15KB.

I'm not absolutely positive my approach to testing this is correct, but it seems logical.

**Comment by samstoller** [comment]
FWIW, I also am interested in this feature and it seems like this would benefit many others as well. Any luck contacting the Google Fonts team? The only way I can see to get in touch is to tweet their Google Fonts account or open up an issue with webfontloader but as noted, it's really a problem with Google's API implementation.

PS - Multiple requests with webfontloader are working since about 5 days ago: https://github.com/typekit/webfontloader/issues/152

**Comment by bramstein** [comment]
Ping: @rsheeter, @kuettel

**Comment by rsheeter** [comment]
I will circulate the notion here. Ty for bringing this up. Sounds like we might need to more clearly define where to report API issues or requests too.

**Comment by rsheeter** [comment]
https://code.google.com/p/googlefontdirectory/issues/list is probably the best place to post any requests related to Google Fonts.

Unfortunately I don't think we will be able to implement this particular request right now so for the time being hiding the multiple requests behind the web font loader might be your best bet.

**Comment by samstoller** [comment]
Thanks. It's definitely an issue with the Google Font API URL so not expecting any changes to be made here. At least not until their API changes.

I opened an issue with them and referenced this issue for good measure: https://code.google.com/p/googlefontdirectory/issues/detail?id=392

Hopefully that will introduce the idea of subsetting multiple fonts in a single request.
