### ISSUE TITLE
Google Font syntax

### ISSUE THREAD

**Issue by courthead** [typekit/webfontloader#207]
The syntax for loading Google fonts described in the README doesn't seem consistent with what Google Fonts wants. This doesn't work:

    WebFont.load({
      google: {
        families: ['Open Sans:n4,n7']
      }
    });

But this does work:

    WebFont.load({
      google: {
        families: ['Open Sans:400,600']
      }
    });

In fact, when you go to the Google Fonts site and prepare to download your selection, it recommends something like the following: `Open+Sans:400,600:latin` (using a `+` instead of a space, and adding the script at the end after another colon).

Spent a while stumbling around trying to figure out why I couldn't get bold working, and I imagine others have done the same, so I think this would be helpful to include in the README.

**Comment by pugsley** [comment]
+1!

**Comment by jeffmcmahan** [comment]
+1

C'mon Google.

**Comment by bramstein** [comment]
This has been fixed now. Thanks for reporting.
