### ISSUE TITLE
Does WebFontLoader provide any benefits when working with “inlined” web fonts?

### ISSUE THREAD

**Issue by alanhogan** [typekit/webfontloader#210]
Currently typography.com (a service from Hoefler & co.) serve font bundles (one to 15 or more font faces) as one .css file, with all font files — in a format suited for the requesting device — inlined as base64 data URIs. 

To be clear, this means that *all* the web fonts are defined *and included* in the same file.

This is… problematic for obvious and some less obvious reasons, most notably for denying browsers the ability to fall back to a FOUT when detecting a slow-loading font.

It seems to me that the font loader would not really be able to help in this case (and nor does it claim to, in my understanding of the README), but a H&co employee referred me here and suggested the use of this loader.

What benefits, if any, can a loader like this provide in such a situation?

**Comment by bramstein** [comment]
You're correct about the downsides of inlining fonts. No matter what you're going to have to wait until the entire CSS file has downloaded. The Web Font Loader will give you font events that will tell you when all fonts have loaded. You can use these events to manipulate styles on your page depending on whether the fonts are loading, have loaded or failed to load.
