### ISSUE TITLE
Add option for data-noprefix for link tags

### ISSUE THREAD

**Issue by zackify** [typekit/webfontloader#214]
I'm guessing it would be implemented around here https://github.com/typekit/webfontloader/blob/b013c1c255dc2b8efefd7a6a003622775426f24a/src/core/domhelper.js#L292

**Comment by bramstein** [comment]
What would that do?

**Comment by zackify** [comment]
We include http://leaverou.github.io/prefixfree/ in our app and it is reloading the call out to google fonts and causing a 403 forbidden because the access-allow-origin header gets stripped by prefix when it is called the second time, just an annoying little bug. We're also seeing that the classes are being applied even though we have classes set to false. Have you ever seen that happen before?

**Comment by bramstein** [comment]
I don't think we should add support for that in the Web Font Loader. We could do it, but I'm sure there are several other libraries that want to do similar things. We can't add exceptions for everything. Is there a way to configure prefixfree to ignore certain URLs?

The `classes` parameter should work. Are you using the most recent version? The parameter was introduced in v1.5.9. I think the Google CDN should have it (or newer versions).

**Comment by zackify** [comment]
It would be useful to add a configuration option for adding custom attributes to the link tag.

**Comment by bramstein** [comment]
I've thought about this a bit more and it doesn't feel right to add special options for this to the Web Font Loader. Sorry, I hope you can resolve the issue some other way.
