### ISSUE TITLE
Is this possible to rename wf-active class?

### ISSUE THREAD

**Issue by marcinant** [typekit/webfontloader#218]
I would like to use Twitter Bootstrap classes for component animations.

There are two classes built in Bootstrap: .fade and .fade.in

Is this possible to customize Web Font Loader and change name of wf-active class to 'in' ?

**Comment by kennethormandy** [comment]
If you’re using the LESS or Sass versions of Bootstrap, you could `extend` the `.fade` classes to `.wf-active` as well, ex:

```scss
.wf-active {
  @extend .fade;
}
```

Alternatively, you could use the WebFontLoader’s events to apply additional classes:

```js
WebFontConfig = {
  active: function() {
    document.documentElement.className += " fade"
    // Or however you want to do this.
  }
};
```

**Comment by marcinant** [comment]
Thank you for your answers.

I used second solution. I got 'fade' class set as default on documentElement, so page has opacity: 0 and then I just add ' in' class to documentElement to set opacity: 1. And I don't need to add anything to css.
