### ISSUE TITLE
What are the java requirements for compiling?

### ISSUE THREAD

**Issue by drewB** [typekit/webfontloader#220]
When I run rake I get the following error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0

What are the java requirements for running the task?  I didn't see it mentioned in
https://github.com/typekit/webfontloader/blob/master/CONTRIBUTING.md

**Comment by bramstein** [comment]
I use Java 8, so that should work. It depends on which version of Java the closure compiler was compiled on. Looks like 51.0 requires at least Java 7.
