### ISSUE TITLE
Loading typekit fonts inside iframe

### ISSUE THREAD

**Issue by Dignifiedquire** [typekit/webfontloader#221]
Hey, 
I'm trying to load on an https connection some fonts from typekit into an iframe. But it seems webfontloader does not request all resources via https when doing so. This is what I'm doing:

```html
<!-- the iframe embed -->
<iframe name="myframe" src="about:blank">
  <head>
    <script type="text/javascript">
    // trying to inject typekit (which works fine outside the iframe
    WebFontConfig = {
      typekit: { id: 'myid' },
      context: frames['top']
    };
    (function() {
    var wf = document.createElement('script');
    wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.5.6/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
    })();
    </script>
  </head>
  <!-- some content set through a script -->
</iframe>
```

I cannot change the `src` of the iframe as the content is dynamically generated from the page surrounding it. Any ideas or pointers would be great!

I've also tried it the other way around: Executing the same script with `context: frames['guides']` outside the iframe. But this fails with the same error.

The error in chrome is always: 

```
Mixed Content: The page at 'https://mypage.com' was loaded over HTTPS, but requested an insecure stylesheet 'http://use.typekit.net/c/9fc772/1w;open-sans,2,VvG:R:i3,VvD:R:i4,VvF:R:n3,V…9355494d244e21a51a65cad9d5ea39af4a06a05f46cdcebc364334daf4db2008553abecfa6'. This request has been blocked; the content must be served over HTTPS.

in myid.js:8
```

**Comment by bramstein** [comment]
Hey,

The Typekit JavaScript looks at the protocol of the page it is embedded in, and if it doesn't find a protocol it defaults to HTTP. The Web Font Loader currently has no way to configure the protocol, but Typekit's JavaScript does. From your example it looks like you're only loading Typekit so you might be able to skip the Web Font Loader by using Typekit directly.

```
<script src="//use.typekit.net/<kitid>.js"></script>
<script>
Typekit.load({
  protocol: "https:"
});
</script>
```

**Comment by Dignifiedquire** [comment]
Thanks for the quick response, but I'm afraid the above doesn't work either. It still tries to request 
```
http://use.typekit.net/c/9fc772/1w;open-sans...
```
over http, even though the protocol is set to `https:` and the surrounding site is served via `https`.

**Comment by bramstein** [comment]
You need the latest version of kit JavaScript for the `protocol` parameter to be supported. If that doesn't work, please write in to support@typekit.com and I'll help you from there. Thanks!

**Comment by Dignifiedquire** [comment]
Mailed you via the support email. Closing this issue as it's not related to the webfontloader directly.
