### ISSUE TITLE
Dynamic Font subsetting and background loadin

### ISSUE THREAD

**Issue by sigginet** [typekit/webfontloader#222]
I just read this article on fonts.com where they describe how they dynamically subset the fonts on initial load to ONLY load the glyphs needed on the page.

http://blog.fonts.com/2015/01/all-the-font-without-the-extra-waiting/

Then in the background, their JS will download the full font file and store it in the cache for faster loading on the next page.

Can this functionality be "borrowed" into the webfontloader?

**Comment by bramstein** [comment]
It could. The Web Font Loader relies on contribution from companies like Google, Typekit, Fontdeck and Monotype, so if anyone is willing to donate time or code to work on something like this, it would be very welcome.

**Comment by snds** [comment]
Was this ever added to webfontloader?
