### ISSUE TITLE
CommonJS module?

### ISSUE THREAD

**Issue by joefreeman** [typekit/webfontloader#226]
I was hoping to be able to `require()` this project's NPM package using Browserify, but I can't get it to work because the project doesn't export a CommonJS module. Would it make sense to?

I think something like (naively adapted from another project) this would cover the AMD/CommonJS/browser cases:

    if (typeof define == "function" && define.amd) {
        define(function() {
            return WebFont;
        });
    } else if (typeof module != "undefined" && module.exports) {
        module.exports = WebFont;
    } else {
        window[exportName] = WebFont;
    }

But I'm not sure where this would need to go.

**Comment by akrawchyk** [comment]
:+1: I can't get webfontloader working with browserify-shim either.

**Comment by moimikey** [comment]
if you're using webpack, you can do this to get it working:

```
// don't forget to npm install --save-dev exports-loader
var WebFont = require('exports?WebFont!webfontloader');

WebFont.load({
  google: {
    families: ['Droid Sans', 'Droid Serif']
  }
});

```

**Comment by bramstein** [comment]
Good idea. Version 1.5.19 now contains a UMD wrapper so it can be used with AMD and browserify.
