### ISSUE TITLE
Slow Server Response Kills DOM Ready

### ISSUE THREAD

**Issue by benjeffreys** [typekit/webfontloader#227]
Hi There.

So, the situation we're in is that Fontdeck is having "issues". This means that the HTTP request for the font is taking a LONG time, and in most cases the request doesn't drop or time out. This means that DOM ready never fires, which means a lot of the code on the rest of the page never fires either.

We do see that "wf-fontinactive" is being added to the body tag and the "inactive" handler is fired.

What would be great is if you could somehow say "if a font request has not responded after XXXXms, then cancel it". This should (hopefully) allow everything else to load and DOM ready to fire.

Maybe this could be done by passing a reference to the request, back to the handler function? Alternatively, it could be an option passed to the configuration object.

Our current workaround is to move the font loading to actually fire on DOM ready.

Happy to provide feedback / test things out!

Cheers for now,

Ben

**Comment by bramstein** [comment]
The `WebFont.load` method takes a `timeout` value, which stops font watching but does not cancel the outgoing request. I'm not sure if there is a way to cancel an ongoing CSS request.
