### ISSUE TITLE
Multiple Fonts with different character ranges

### ISSUE THREAD

**Issue by ungeruehrt** [typekit/webfontloader#229]
Hi there,

I’d like to use two different fonts from google but with different character ranges –

    families: ['font1:400','font2:300'],
    text: 'abcdefghijklmnopqrstuvwxyz'

wouldn’t work, since then the same range would be used for both fonts.
Do I have to add the whole script twice to my website or is there a more clever way to get this solved?

**Comment by mrbinky3000** [comment]
+1 for this question

**Comment by bramstein** [comment]
You can only do this by calling `WebFont.load` multiple times. This is a limitation in Google's API. It doesn't allow per font subsets. Calling `WebFont.load` multiple times will insert two `<link>` elements, each with its own subset.
