### ISSUE TITLE
specifying subsets doesn't really work

### ISSUE THREAD

**Issue by ilanle** [typekit/webfontloader#230]
Hey dude,
I tried specifying fonts and subsets just like Google recommends, however this doesn't work for me, in the sense that ext-latin for example is always loaded on document ready which is too late for me.
The great thing about this library in my opinion is that I can dl the fonts and load them prior to document ready.

Using it just like Google suggests from google fonts :+1: 		
WebFont.load({
		google: {
				families: [ 'Lora:400,700,400italic,700italic:latin,latin-ext,cyrillic' ]
			}
	});

however, all fonts load before document ready except for latin-ext, which only loads on document ready . and I often get a FOUT

http://imgur.com/Gb8UXPI

thank you,
Ilan

**Comment by ilanle** [comment]
BTW,
If I manually specify characters with the text field, I get a custom set which does include all of the characters and it IS loaded early as I wish, but I don't know whether I need to /can specify all (don't even know what is the complete set).
Thanks

**Comment by joeyfromspace** [comment]
Are you using the Google APIs CDN? I was having this problem using that one. Then I realized Google's hosted library is several versions old. I installed locally and it now works much better for me.

**Comment by bramstein** [comment]
The Google module inserts a stylesheet link, which contains external references to font files. These will only be downloaded by the browser if they are needed. This depends on the DOM and CSSOM, so the browser will wait until those are constructed. If you want to download fonts earlier, you'll need to preload them manually.
