### ISSUE TITLE
Google's hosted version is 5 releases behind this repo

### ISSUE THREAD

**Issue by callumlocke** [typekit/webfontloader#232]
The recommended Google-hosted webfontloader is at [v1.5.10](https://developers.google.com/speed/libraries/devguide#webfont), released over 3 months ago.

Since then there have been [five patches](https://github.com/typekit/webfontloader/releases).

Can this be updated?

**Comment by joeyfromspace** [comment]
I agree. Version 1.5.10 only loads weight normal when using fvd notation for me, but it works great with 1.5.18.

**Comment by bramstein** [comment]
The Google CDN usually follows Google's internal release schedule. Sometimes that means it is out of sync with the releases in this repository. I'll ask them if they can push the latest release online. Thanks for bringing this up.

**Comment by bramstein** [comment]
The CDN should have the latest version now.
