### ISSUE TITLE
Provide webfontloader.js in uncompressed format

### ISSUE THREAD

**Issue by marcinant** [typekit/webfontloader#233]
As in topic. `webfontloader.js` is provided in uglified format.
It's hard to provide this code as a part of a bigger bundle with sourcemaps as it's not possible to provide preview of this file in not uglified form.

Please provide webfontloader.js in standard format. Provide webfontloader.min.js as an option.

**Comment by bramstein** [comment]
Thanks for the suggestion. This project uses Closure compiler, so the unminified source is not suitable for minification with other minifiers. If you are using Closure Compiler you should be able to use the files in src directly. I'm not against making unminified files available, but I'm not sure there is much value in it.
