### ISSUE TITLE
Google Webfonts has no plans to support FVD

### ISSUE THREAD

**Issue by mrbinky3000** [typekit/webfontloader#239]
I had a conversation with the folks at Google:

https://github.com/google/fonts/issues/20#issuecomment-96669588

They have no plans for supporting FVD syntax.  In fact, the URL generated by webfontloader is always interpreted with the weight 400.

For example:

```javascript
WebFont.load({
    google: {
        families:['Open Sans:i6']
    }
});
```

Loads the italic version of Open Sans with a font-weight of 400, not 600.

To fix the problem, webfontloader should translate the FVD syntax into long form when contacting Google.

http://fonts.googleapis.com/css?family=Open+Sans:600italic

Something like this might help:

```javascript
/**
 * Takes a FVD (font variation description) and translates it into a longform.
 * Google does not accept FVD syntax.  If you use it, it just returns
 * the n4 version of the font.
 *
 * Using this function: 'n3,n4,i4' becomes '300,400,400italic'
 *
 * @see https://github.com/typekit/fvd
 * @param  {string} fvd An FVD definition like 'n4,n5,i7'
 * @return {string}     long form of FVD.
 */
fvdToLongFormat = function (fvd) {
	var bits = fvd.split(',');
	var ret = [];
	bits.forEach(function(bit){
		var matches;
		if ((matches = /([nio])(\d)/.exec(bit)) !== null) {
			if (matches[1] === 'i' || matches[1] === 'o') {
				ret.push( (matches[2]*100) + 'italic');
			} else {
				ret.push(matches[2]*100);
			}
		}
	});
	return ret.join(',');
};
```

**Comment by bramstein** [comment]
Thanks, Google has updated the documentation.
