### ISSUE TITLE
Font not loaded when css file is specified in "urls" - IEMobile 11.0 - "mobile version"

### ISSUE THREAD

**Issue by on6qd** [typekit/webfontloader#244]
Environment:
- Windows phone 8.1 - IEMobile 11.0 
- Css file is specified in "urls"
- Webfonts are stored on same server as website. 
- "mobile vesion" in IE browser settings is set.

Symptom:
- Font is not loaded. (website uses fallback font)

Remark:
- When changing the IE browser settings to "desktop version", the font is loaded correctly.
- When  loading css file conventionally in the head section of the html document, font loads correctly in both "mobile version" and "desktop version" mode.

Tested with multiple versions of webfontloader (1.5.14 - 1.5.18)

**Comment by bramstein** [comment]
Thanks for reporting this. This looks like a failure to detect whether or not a browser supports web fonts. This detecting is done using UA sniffing and it seems to fail in this case. I'll see if I can fix that (we should really get rid of UA sniffing, but that's a larger project).

**Comment by bramstein** [comment]
Do you happen to have the user agent string for your device? I tried a couple, but all the ones I've tried are detected correctly.

**Comment by on6qd** [comment]
That should be:

mozilla/5.0 (Mobile; Windoes Phone 8.1; Android 4.0: ARM; Trident/7.0; Touch; rv:11.0: IEMobile/11.0: Microsoft; Lumia 535 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebkit/537 (KHTML, Like Gecko) Mobile Safari/537

Regards

Bart

**Comment by bramstein** [comment]
Oh wow. That's a great example of why user agent sniffing is a bad idea. I'm not sure I can fix the UA detection for that one.

**Comment by on6qd** [comment]
Purchased this phone as a "test device" because a client was informing me fonts not loading on “Nokia smartphones”, (model not specified).

Therefore this problem is probably not related to this specific model only - Microsoft (Nokia) 535 - but to any Windows Mobile 8.1 phone in “mobile version” mode (default).

Regards

Bart

**Comment by bramstein** [comment]
Just a quick update, I decided to fix this the proper way, and the changes will go out soon (see #245).

**Comment by on6qd** [comment]
Nice!

**Comment by bramstein** [comment]
This should be resolved in the latest version (v1.6.3). Thanks again for reporting this issue.

**Comment by on6qd** [comment]
Tested on Microsoft (Nokia) 535 and works now.

Thanks for the effort!
