### ISSUE TITLE
Wrong value of this passed to module

### ISSUE THREAD

**Issue by getdave** [typekit/webfontloader#248]
I'm using webfontloader via WebPack CommonJS module. Webpack compiles fine but when I load up the JS on the page I get an error

`Uncaught TypeError: Cannot read property 'userAgent' of undefined`

So `userAgent` lives on `window.navigator` so I checked to see what `window` referred to inside the `webfontloader.js` file in the `node_modules` directory and I see it's set to `this` which is passed in via the module closure.

If I alter the `this` to `window` and recompile it works fine.

I'm not sure if this is a webfontloader issue or a misconfig of WebPack. However I've noticed a similar issue https://github.com/typekit/webfontloader/issues/246 which indicates there may have been a similar issue before?

Please can you advise? Web Font Loader v1.6.0

__Update:__ may relate to https://github.com/webpack/webpack/issues/97

**Comment by bramstein** [comment]
Could you try v1.6.2 to see if this is fixed?

**Comment by getdave** [comment]
Unfortunately the same error persists. Logging `this` return a plain JavaScript object `{}`

**Comment by bramstein** [comment]
Hmm, there is only one place in the code that reads `userAgent` and it correctly references `window.navigator.userAgent`. It looks like webpack isn't setting up the window correctly in this case.

**Comment by getdave** [comment]
I believe it is a webpack issue. Closing.
