### ISSUE TITLE
window.navigator is undefined

### ISSUE THREAD

**Issue by dhritzkiv** [typekit/webfontloader#249]
I seem to be getting this error: 
`TypeError: undefined is not an object (evaluating 'window.navigator.userAgent')`

And fonts don't render at all.

Using v1.6.2 with Browserify

**Comment by bramstein** [comment]
Is `navigator` not available on the `window` object in browserify? Is the global `navigator` object available?

**Comment by dhritzkiv** [comment]
`navigator` is available on the `window` object in browserify, yes. And the global `navigator` object is available (aka without doing `window.navigator`), however:

Poking around in Chrome's debugger, and inspecting the scope in the function `FontWatchRunner.getUserAgent` (which gets inlined as simply `window.navigator.userAgent` in the compiled/minified code), I saw that the `window` variable passed-in is an empty object, for some reason. Also in this scope, I can see that the global object is, in fact, available (so, you should be able to simply access `navigator`).

[You can poke around the browserify build here](http://requirebin.com/?gist=40d1b77bd39b45ff3996) (open console to see the errors and output)

So, somewhere along the way, something is assigning an empty object to the `window` variable.

Also, as an aside, would it be possible for the main script file (declared in package.json) to be an un-minified version of the code? This would make debugging future issues easier, as well as seeing diffs in the post-compilation code. Minifying the code would then be the responsibility of each "consuming" developer.

**Comment by waitingallday** [comment]
I'm getting the same on v1.6.x, switching back to v1.5.21 removed the error for me.

**Comment by bramstein** [comment]
I think I resolved this issue in v1.6.3. Could you try upgrading and check if it is resolved? Thanks!

**Comment by dhritzkiv** [comment]
Resolved! Thanks.
