### ISSUE TITLE
Cannot call active for khmer font

### ISSUE THREAD

**Issue by sapics** [typekit/webfontloader#252]
I would like to load khmer google font like `Moul`.
I use a recommended method `Moul:400:khmer` which is introduced in #202.
But WebFont call `inactive` function as http://jsfiddle.net/sapics/oxgxehev/8/.

Is there other method to call `active`?

ADD: I am using Google Chrome in Windows8.1

**Comment by mdzzohrabi** [comment]
I have same issue on custom module. fonts loaded and rendered successfully but Font Loader doesn't trigger `active` event.

*Console log :*
```
Loading
Yekan n4
InActive
```

```coffee
WebFontConfig =
    custom:
        families: [ 'Yekan' ]
        testStrings:
            'Yekan': '\u0662\u0633'
        urls: [ 'fonts.css' ]

WebFont.load
    loading: () -> console.log 'Loading'
    active: () -> console.log 'Active'
    inactive: () -> console.log 'InActive'
    fontactive: () -> console.log 'Active font'
    fontloading: (font,fvd) -> console.log font,fvd
    custom:
        families: [ 'Yekan' ]
```

**Comment by bramstein** [comment]
@mdzzohrabi Do you have a sample page somewhere so I can take a look?

**Comment by mdzzohrabi** [comment]
@bramstein http://lab.mdzzohrabi.ir/webfontloader.html. Check it out and enjoy it ;-)

**Comment by sapics** [comment]
@bramstein Thank you for your great works!
Now, my test case works well!
