### ISSUE TITLE
Update CDN version link in readme

### ISSUE THREAD

**Issue by klihelp** [typekit/webfontloader#253]
CDN link in readme point to version 1.5.18.

A more recent CDN link can be find  at http://cdnjs.com/libraries/webfont

**Comment by michaelthorne** [comment]
@klihelp current version is 1.6.3 https://github.com/typekit/webfontloader/blob/master/package.json#L3

**Comment by michaelthorne** [comment]
But I see [webfont.js](https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js) still loads `1.5.18`

**Comment by bramstein** [comment]
The Typekit release schedule is usually out of sync with the Google one. It usually takes 1-2 months for new versions to be available on the Google CDN.
