### ISSUE TITLE
Bold variant not loading

### ISSUE THREAD

**Issue by howlingmad** [typekit/webfontloader#254]
I am trying to load Open Sans from google fonts in both the 400 and 700 weights, but only seem to get the 400 weight showing up properly

http://jsfiddle.net/y52977ob/3/

**Comment by edhenderson** [comment]
Loads fine for me. Maybe check your Dev Tools, see if its failing to download? What OS/browser you viewing on?

**Comment by sapics** [comment]
Please look at http://jsfiddle.net/sapics/y52977ob/15/.
 In jsfiddle, we cannot use `custom` but `google` for `Open Sans`.

**Comment by howlingmad** [comment]
It's downloading fine, I get the open sans, but no bold variant. This is on Chrome (latest) on Yosemite. Works fine on Firefox

![example](https://cloud.githubusercontent.com/assets/853933/8302482/a069e248-198e-11e5-8412-d6d3df6f1429.png)

**Comment by howlingmad** [comment]
OK fantastic, thanks
