### ISSUE TITLE
Is it possible to used cached fonts to avoid FOUT/FOIT?

### ISSUE THREAD

**Issue by FStop** [typekit/webfontloader#257]
We're using web font loader in a project and have it set up so that fallback fonts are visible until web fonts load, which results in FOUT. We decided that faster viewing of content was better than hiding web fonts until they are loaded.

But FOUT happens on every page load, and it seems like we should be able to avoid it if the fonts are already cached.

**Comment by bramstein** [comment]
You should be able to do this if you can manage to insert the @font-face rules (with the cached font files) before the browser starts rendering. This means your logic should be in the <head> element and fire very early.
