### ISSUE TITLE
Appending font ruler span can cause CSS selector issue

### ISSUE THREAD

**Issue by joelrich** [typekit/webfontloader#258]
We use the adjacent CSS selector (class-1 + class-2) and run into a problem in Chrome where this selector is interrupted by the font ruler span elements which are unluckily inserted exactly between the first and second element. Is there a reason why the font rulers spans can't be appended at the beginning of the body? This would solve our issue.

**Comment by christanto** [comment]
Just to add.
As long as the span is added in predictable location/way, it would be good. That way we can anticipate.

**Comment by bramstein** [comment]
I think they're more likely to disrupt the flow of the page when they're inserted at the beginning. You should get consistent behaviour when you call `WebFont.load` after (or before) you've inserted your content.
