### ISSUE TITLE
Why typekit is polling so much?

### ISSUE THREAD

**Issue by dok** [typekit/webfontloader#267]
See this timeline profile:

![screen shot 2015-08-18 at 11 34 10 am](https://cloud.githubusercontent.com/assets/1214868/9339121/40f3cd2a-459d-11e5-86a4-0af8360d3369.png)

All of those little orange clicks are from a result from webfont.js (using 1.6). This polling occurs over a period of ~3 seconds, which is hitting our performance and holding up our rendering. Can someone help me on how to alleviate this issue?

Thank you,

**Comment by bramstein** [comment]
This polling is caused by the font load detection code. As a side effect the polling causes a reflow (which is expensive in most cases). Work is being done in #262 to use the native font watching which will alleviate this in browsers that support the native API.
