### ISSUE TITLE
Google module: Set text for certain family (or better /variant).

### ISSUE THREAD

**Issue by seanhak** [typekit/webfontloader#269]
Is it possible to set character loading for only one of the families (sometimes you might want to embed light font for certain characters, like numbers as well)? 
This is what I'm trying to do (obviously will overwride the first one).
````
WebFontConfig = {
    google: { families: ['Lato:400,700,400italic,900:latin'] },
    google: { families: ['Ek+Mukta:800:latin'], text: '0123456789' }
};
````

Thanks

**Comment by bramstein** [comment]
No, that's currently not possible without calling `WebFont.load` twice. This is mostly because the Google Fonts API only accepts a single `text` parameter.
