### ISSUE TITLE
font variation description is always "n4" for webfont loader with Monotype module

### ISSUE THREAD

**Issue by ramghaju** [typekit/webfontloader#272]
Webfont loader with Monotype module always shows "n4" as font variation description. Monotype users can enable family grouping on their project after adding fonts on the project. When this project is used with google webfont loader, it always shows "n4" as font variation description. So, it is firing single font event for different variation of same font-family. Please check attached image.
![webfontloader](https://cloud.githubusercontent.com/assets/13748006/10048616/86229004-6233-11e5-8e7e-e636232a78a1.PNG)

**Comment by bramstein** [comment]
The Monotype module does not pass font variations to the web font loader, so it always defaults to `n4`. See: https://github.com/typekit/webfontloader/blob/master/src/modules/monotype.js#L65

**Comment by ramghaju** [comment]
Yes, you're right. We would like to update Monotype module to pass font variation. So that it will work correctly.

**Comment by bramstein** [comment]
This has been released, closing the issue.
