### ISSUE TITLE
.wf-loading class is removed prematurely

### ISSUE THREAD

**Issue by on6qd** [typekit/webfontloader#283]
When multiple fonts are loaded.

wf-loading class is removed and wf-active class is set after the **first** font becomes active, and while other fonts are still loading.

It is expected wf-loading class is present until all fonts are loaded.

Tested with fonts loaded from typekit **and** custom fonts loaded from webserver.

**Comment by bramstein** [comment]
This is by design (though you can argue it is incorrect --- and I agree). Changing it now would change the expected behaviour for many of our users, so it isn't something we can do right now.
