### ISSUE TITLE
Versions >1.6.8 call fontinactive for fonts that are already in the page

### ISSUE THREAD

**Issue by grabks** [typekit/webfontloader#284]
Versions of WebFontLoader 1.6.8 and forward appear to have an issue when loading a font that is already available. [This jsfiddle is a great example.](http://jsfiddle.net/y87zja8j/)

The jsfiddle loads some variants of the Roboto font itself via a `<link>` tag, includes version 1.6.10 of the WebFontLoader (also tried with 1.6.8 and 1.6.7), and attempts to load the Roboto font via WebFont.load. As you can see from the console messages, the version in that jsfiddle will report the Roboto font as inactive. When I tested version 1.6.7, it did indeed call the correct callback (fontactive).

**Comment by omo** [comment]
Probably a regression from my change. Let me see.
