### ISSUE TITLE
Versioning and Cache Max-age

### ISSUE THREAD

**Issue by superpoincare** [typekit/webfontloader#286]
I think Webfontloader seems to violate the caching rules as given here: 

http://www.paulirish.com/2009/caching-and-googles-ajax-libraries-api/

This request caches for 1 year, when it should instead cache for 1 week(?). 

http://tools.pingdom.com/fpt/#!/DE4IT/ajax.googleapis.com/ajax/libs/webfont/1/webfont.js

**Comment by bramstein** [comment]
Thanks for the report. Unfortunately, we (Typekit) do not control Google's CDN, so your best chance to get it fixed is to contact Google.
