### ISSUE TITLE
Multiple Font Loading Error

### ISSUE THREAD

**Issue by XanderRock** [typekit/webfontloader#288]
Hi,

I've just updated to the latest version. However, now multiple loads don't work. It used to work normally. 

What I'm trying to do is, to use "WebFont.load" in different areas. And if the same font is loading on different areas, "active" event does not return. Instead it returns the "inactive" event. 

For example ;

all_fonts is an array of fonts. Lets say I have "Open Sans" in this "all_fonts" array. And I load it this way ;

	WebFont.load({
		google: {
			families: all_fonts,
		},
		fontactive:function(font_name, fvd){
			//Do Nothing
		},
		fontinactive:function(font_name, fvd){
			//Do Nothing
		},
		active: function(){
			//Fonts active
		},
		inactive: function(){
			//Some Fonts active
		}
	});

And let's say on some other area, I'm loading "Open Sans" and "Roboto". I use the same function of course. But this time, it returns "inactive".

As I understand active and inactive events will be triggered if font is active. Which means, if a font loaded earlier that font is active. And it should trigger "active" event. But it returns "inactive". Also "fontinactive" function returns the earlier activated font name. It's like the font loading failed. However, font just loaded earlier. And it's actually active.

I also saw there used to be some issues and fixes. This seem to be related to this issue as well ;

https://github.com/typekit/webfontloader/issues/152

However, the latest version still giving this issue.

**Comment by bjornbos** [comment]
I have the same problem, it's messing up our error logging.

**Comment by webyak** [comment]
Same here. Currently using https://github.com/bramstein/fontfaceobserver as a workaround.

**Comment by bramstein** [comment]
This should be fixed in v1.6.11.
