### ISSUE TITLE
Old Version on Google Hosted Libraries

### ISSUE THREAD

**Issue by ungeruehrt** [typekit/webfontloader#292]
Hi,

I’m just wondering why the latest version available on Google Hosted Libraries is 1.5.18 while the most recent version is 1.6.15. Is there any reason why the script on Google Hosted Libraries is that much older?

**Comment by bramstein** [comment]
The Google CDN is controlled by Google, and as such it follows Google's release cycle. This means it is sometimes out of sync with the latest version in this repository. Apart from self-hosting the Web Font Loader, there's unfortunately not much we can do about it.
