### ISSUE TITLE
.wf-active never appears using Fonts.com module

### ISSUE THREAD

**Issue by extractachris** [typekit/webfontloader#294]
I am using the Fonts.com module to load my fonts:

```
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js"></script>
<script>
  WebFont.load({
    monotype: {
      projectId: 'xxx-xxx-xxx'
    }
  });
</script>
<noscript>
  <link type="text/css" rel="stylesheet" href="//fast.fonts.net/cssapi/xxx-xxx-xxx.css"/>
</noscript>
```

The fonts load, however the only class name that is appended to the `html` tag is `.wf-inactive`.

Not sure if I am missing something?

**Comment by mhmli** [comment]
Experiencing the same issue here. All browsers.

**Comment by mhmli** [comment]
Update: using the latest version from Github solves the problem. The documentation and the Google-hosted version are out of date. (See #292 as well.)

**Comment by bramstein** [comment]
Fonts.com recently updated their API, but the latest version of WFL that supports it isn't on the Google CDN yet. It should be there early January.

**Comment by extractachris** [comment]
Updating (and self-hosting) the latest version fixed my issue, thanks.
