### ISSUE TITLE
Google fonts not loading in Microsoft Edge

### ISSUE THREAD

**Issue by hankmander** [typekit/webfontloader#295]
Have an isolated fiddle here:
http://jsfiddle.net/5dmg2nub/5/

Callbacks (fontactive & fontinactive) are not called and font is not downloaded.
Surprisingly it works well in IE11.

**Comment by jeremyfrank** [comment]
This also seems to be happening for fronts from fonts.com (monotype).

**Comment by mhmli** [comment]
The linked version of webfontloader.js is very old. Suggest you try the current version.

**Comment by jeremyfrank** [comment]
I'm using [1.6.20 from cdnjs](http://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.20/webfontloader.js).

**Comment by jeremyfrank** [comment]
@mhmli Disregard the MS Edge fonts.com issue. It seems to be problematic only on my virtual machine. Testing via browserstack shows the web fronts loading from fonts.com and displaying correctly. Sorry for the false alarm!

**Comment by bramstein** [comment]
Looking at the network chart it does seem to download the CSS, which means the Web Font Loader is working correctly. Why the font does not render is another issue. I'm guessing it is either a problem with Google Fonts, or Edge. Could you open an issue with either of those teams? Unfortunately, this isn't something we can fix.

**Comment by priyankamotiani** [comment]
Facing same issue for IE Edge, is there any update?
