### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by cbranje** [typekit/webfontloader#296]
I'm getting this exception when I try and user webfontloader.js

Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by bjnsn** [comment]
I ran into this also. For me it was the result of using AlmondJS (RequireJS) with the newest CND version of webfontloader (1.6.16). It is making a define call with an undefined second parameter. Reverting to 1.5.18 fixed this for me.

**Comment by cbranje** [comment]
I'm already using 1.5.18. Still getting the error.

**Comment by bjnsn** [comment]
Hmmm. For me, this was being triggered in a call to AlmondJS define method. Where is it coming from for you?

**Comment by bjnsn** [comment]
Actually, yours looks like a different error than the one I was getting. Mine was

    Uncaught TypeError: Cannot read property 'splice' of undefined

from the AlmondJS define method. Not `split`.

I've filed an [https://github.com/jrburke/almond/issues/112](issue) over there to clarify the correct procedure for interfacing between AlmondJS and UMD modules.

**Comment by bramstein** [comment]
The Web Font Loader is not using `splice`, and it looks like you've already tracked down the issue. Closing this ticket.

**Comment by bjnsn** [comment]
My `splice` is solved; but I believe @cbranje issue is still outstanding. Not sure if @cbranje can give more details...
