### ISSUE TITLE
Firefox reports loading fonts multiple times

### ISSUE THREAD

**Issue by damonbauer** [typekit/webfontloader#297]
I'm seeing an issue in Firefox 43.0.4 where the network tab shows 3 requests for each font loaded from Google. Chrome & Safari latest don't have this problem. I've tried using webfontloader version 1.5.18 & 1.6.20; the issue occurs in both.

I'm not sure if this is an issue with Firefox's Dev Tools, Google Fonts or webfontloader. I have a hunch it's Firefox, but I just want to make sure.

My webfontconfig:
```js
WebFontConfig = {"google":{"families":["Open Sans:normal,bold,italic,bolditalic"]},"typekit":{"id":"kxz1dcg"}};
```

Firefox:
![screen shot 2016-01-06 at 4 03 10 pm](https://cloud.githubusercontent.com/assets/368723/12156181/07535ef8-b48f-11e5-8ad1-21a7588175ae.png)

Chrome:
![screen shot 2016-01-06 at 4 03 55 pm](https://cloud.githubusercontent.com/assets/368723/12156192/1e5763ce-b48f-11e5-9503-0cc886cfc29b.png)

**Comment by efreed** [comment]
I'm having the same issue.  Both Firebug, and FF's built-in inspector show up to 16 times more font loads than Chrome.

Is this really loading the fonts more, or is it a false indicator in the inspector window?

**Comment by bramstein** [comment]
I can't reproduce this in the latest Firefox version, so I'm guessing it was a temporary bug.

**Comment by damonbauer** [comment]
Hmmm.. I'll keep an eye out, but it's still occurring for me in Firefox 43.0.4.

<img width="1280" alt="screen shot 2016-01-25 at 7 56 21 pm" src="https://cloud.githubusercontent.com/assets/368723/12570520/e6af4f18-c39d-11e5-9089-95b741d1a9d4.png">

**Comment by mariuslazar93** [comment]
Still happening for me in Firefix Developer 46.0a2. FF makes 12 requests while Chrome make just 3 requests for http://fonts.googleapis.com/css?family=Lato:300,400,700
![2016-02-08_1730](https://cloud.githubusercontent.com/assets/11423217/12889932/f4525880-ce89-11e5-92b0-9c665dbf5a22.png)

**Comment by erklat** [comment]
Also we just noticed this while debugging today. On changing font css properties, Firefox makes new request.

**Comment by guanlun** [comment]
Found on Chrome (Version 51.0.2704.103 (64-bit)) that each time `WebFont.load()` is called the number of request would increase by 1.

Calling the first `load` only fires 1 request, 2 for the 2nd, etc.

However when I tried with Safari it seems fine. Only 1 request no matter what.

**Comment by ghost** [comment]
I see this in 2024, in Firefox 127. This site, which seems to have nothing to do with typekit:

https://www.meredithfrederickart.com/
