### ISSUE TITLE
Custom module: all variants marked active when another variant is loaded

### ISSUE THREAD

**Issue by chrisbateman** [typekit/webfontloader#299]
For example, when loading 2 variants of a particular font-family:

```javascript
WebFont.load({
    custom: {
        families: ['Archivo Narrow:n4', 'Archivo Narrow:i4']
    }
});
```

As soon as 1 of the fonts loads, both will be marked as active.

The same issue occurs if one of the fonts is already on the page, as in this example: https://jsfiddle.net/3y4mdyaz/1/

Note that I'm using a google font in these examples, but I'm using local fonts in reality.

**Comment by bramstein** [comment]
@chrisbateman That's an unfortunate side effect of the browser's font matching algorithm (and sometimes faux style generation). As soon as one of them loads the browser will apply it to the page even though the style might not match. This generates a false positive. You can work around this issue by giving each variation a unique name (e.g. "Archivo Narrow" and "Archivo Narrow Italic").
