### ISSUE TITLE
(Google Fonts module) - Fonts without latin subset receive "inactive" events in Chrome

### ISSUE THREAD

**Issue by shyndman** [typekit/webfontloader#301]
http://codepen.io/shyndman/pen/GoOBzZ?editors=101

The fonts are downloading successfully. Any thoughts on why this might be?

**Comment by shyndman** [comment]
This is only happening in Chrome. Safari and Firefox work perfectly.

**Comment by shyndman** [comment]
Looks like this has to do with the use of HTML entities with the native loader in Chrome.

Replacing `'&#x1780;&#x1781;&#x1782;'` with `'កខគ'` results in the active event being fired.

**Comment by bramstein** [comment]
Thanks for reporting this. It's a bug and fixed in #350.

**Comment by shyndman** [comment]
Thanks Bram. :)

**Comment by shyndman** [comment]
For posterity, fixed in #305.
