### ISSUE TITLE
[Revisit]: add bower package file

### ISSUE THREAD

**Issue by KLVTZ** [typekit/webfontloader#302]
> Continuation of #208 

Problem
-----------
As addressed by @bramstein in the previous discussion, users have the capability of pulling a version of Web Font Loader through third-party maintainers: http://bower.io/search/?q=webfontloader . If one of these are maintained by an official maintainer: apologies for overlooking.

The issue is that these packages are simply under the control of maintainers who may not be directly part of the project. If we take a look at [bower-webfontloader](https://github.com/mdarse/bower-webfontloader), the project has not been updated to the latest release. the case is similar for others.

Solution
-----------
If we include a `bower.json` file with this project, official maintainers who tag a release will be reflected in an official package on bower. End-users will have the confidence of knowing the package they install is up-to-date with the repo that maintains it. Else, it's cat and mouse.

Happy to hear your thoughts!

**Comment by febLey** [comment]
I think this is a must-have

**Comment by troygrosfield** [comment]
:+1:

**Comment by bramstein** [comment]
Alright, we can add a bower file as long as we don't need to maintain a bower.json file with a separate version number. Anyone up for opening a pull request?

**Comment by bramstein** [comment]
This has been added.
