### ISSUE TITLE
Not working for typekit

### ISSUE THREAD

**Issue by brickfungus** [typekit/webfontloader#307]
I'm trying to get typekit to work.  webfontloader is loading up google fonts perfectly, but I'm having issues with typekit

Simple code like this:
```
WebFont.load({
 typekit: {
     id: lib.Code
   }
});               
```

The url it's building is: https://use.typekit.net/c/47b49a/1w;museo-sans,7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191,Py8:W:n1/d?3bb2a6e53c9684ffdc9a9af11f5b2a6290826e84c363a71fe46ed23db0c849f636a116464660d22eaeb6f1aae912ceb2860c92fd6381f57b0a079008a1bfb19a5e25e68b308e93ba2295c8
Is that correct?  I though it was supposed to more like: https://use.typekit.net/{kit-id}.js

Anyways, the URL it's building is giving me a 403 Fobidden.

Is there something I'm doing wrong here?

**Comment by bramstein** [comment]
The URL looks correct; it is built by Typekit to load fonts. A 403 usually indicates the domain in your kit does not match the domain you're serving the website from. If you write in to support@typekit.com we'll help you further.
