### ISSUE TITLE
Track non-minified source

### ISSUE THREAD

**Issue by IgorNadj** [typekit/webfontloader#315]
I suggest this repository contain both the human-readable distribution (after combining) and the minified distribution (which it already does). This would follow convention and make debugging easier.

**Comment by bramstein** [comment]
This project is using Closure Compiler and non-minified versions aren't that useful (since they require the whole Closure compiler setup). They simply won't work. I could add a debug version, but that'll have mangled variable names which makes debugging hard.

**Comment by prewk** [comment]
This is a serious problem for us because currently I'm getting some strange unhandled Promise rejection error inside of the minified code, and there's no way for me to interpret the problem and solve it :/

`Paused on promise rejection: ''.` somewhere after Q.start
