### ISSUE TITLE
1.6.22 - Promise, IE note, etc.

### ISSUE THREAD

**Issue by bazineta** [typekit/webfontloader#316]
In that the 1.6.22 release uses a Promise object, suggest modifying the browser support section to indicate that a polyfill will be required for IE, unless I misunderstand things.

**Comment by bramstein** [comment]
@bazineta The Web Font Loader will detect support for promises, and if it isn't present it'll fall back on another method of detecting font loads. So there is no need to include a Promise polyfill.
