### ISSUE TITLE
Random "Promise.race is not a function" error

### ISSUE THREAD

**Issue by pocesar** [typekit/webfontloader#322]
Typekit seems to be randomly breaking my webapp. I use bluebird on the app with Bluebird.noConflict(), it seems that there's a racing condition where Typekit tries to use the .race on Bluebird, and when it tries to use it, it's no longer available or it's trying to use the native implementation of Promise, depending on the timing of the Bluebird.noConflict() call, it's completly random.

The problem seems to happen only in Firefox 46 and Edge. 
Couldn't reproduce locally in Chrome, only in the production server.

**Comment by bramstein** [comment]
Hmm, that is worrisome. Do you have a test page so I can take a look? The Web Font Loader should only try to use Promises when the CSS font loading API is present.

**Comment by pocesar** [comment]
latency plays the biggest role. 140ms - 180ms is enough for the problem to happen in a more consistent manner. using the rate limiting in Chrome I was able to reproduce it. 
I use the current code to load the fonts:
```js
try{
  Typekit.load({ async: true });
}catch(e){}
```
I tried to move this code around to see if it would make a difference, it doesn't. Tried to call it immediately after Bluebird.noConflict() (inside `angular.bootstrap`), but it didn't make a difference either, so the solution I found was to use the NPM version of Bluebird, so it won't export globals (and overwrite the window.Promise before the `Bluebird.noConflict()` call ).

**Comment by antgonzales** [comment]
I'm seeing this problem show up in our app's error reporter (Raygun). We currently load the fonts using the [Get Started](https://github.com/typekit/webfontloader#get-started) method and not NPM.

**Comment by antgonzales** [comment]
@pocesar can you provide details of why this issue was closed?

**Comment by pocesar** [comment]
I'm not using globals anymore (and nobody shouldn't at least) when doing frontend code. that alone fixes any inconsistencies with global only packages (like this one)
