### ISSUE TITLE
get number of fonts for given typekitId

### ISSUE THREAD

**Issue by jedierikb** [typekit/webfontloader#326]
Is there a way for webfontloader to reveal the number of fonts it is downloading for a given typekit-id?

Trying to calculate, while fonts load, how close we are to complete.  The typekit-ids are being data driven so my loader does not know how many fonts to expect.

**Comment by bramstein** [comment]
Sorry, that's not currently possible. The Typekit API doesn't expose the number of fonts publicly, but we'll consider changing that in the future.
