### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object Undefined]

### ISSUE THREAD

**Issue by mystvearn147** [typekit/webfontloader#346]
warning comes when using bluebirdjs in development mode

Warning: a promise was rejected with a non-error: [object Undefined](No stack trace)
From previous event:
    Q.prototype.start@https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js:21:1518
    ra/<@https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js:26:37

**Comment by jeremejevs** [comment]
Why did you close this? Have you resolved it somehow?
