### ISSUE TITLE
WebFontLoader still give me render block error 

### ISSUE THREAD

**Issue by MiguelCrespo** [typekit/webfontloader#356]
Hi. sorry if this is not the place to place this issue but I already asked in stackoverflow with no answers.

I'm having an issue with the Webfontloader (I think is an issue).

I am trying to remove the "Script as render blocking file" error from Google Pagespeed insight so I decided to use Webfontloader to load the fonts that I need. And I am using it with webpack with the code below:

   ```
import WebFont from'webfontloader';

       WebFont.load({
            google: {
               families: ['Roboto:300,400,700']
           }
       });
```

```
body {
  font-size: 1.4rem;
  font-family: sans-serif;
}

.wf-active body {
  font-family: 'Roboto', sans-serif;
}
```

But I still getting the same error with that font and I thought that this library was suppose to fixed this issues or am I doing something wrong?

https://developers.google.com/speed/pagespeed/insights/?url=http://personal-miguel.s3-website-us-west-2.amazonaws.com/

Thank you for your attention.

**Comment by southwolf** [comment]
@MiguelCrespo How was the problem solved? Can you share some information? Thanks

**Comment by dcsaszar** [comment]
According to the given link the problem is unsolved. See also #360
