### ISSUE TITLE
How to load Material Design Icons?

### ISSUE THREAD

**Issue by dinnouti** [typekit/webfontloader#368]
What is the best way to load the material design icons? Below is a plain HTML example.

`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

**Comment by adamreisnz** [comment]
Was wondering the same thing, but looks like just including it in the list of fonts seems to work.

**Comment by venky216** [comment]
` 
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js">
  </script>
  <script>
    WebFont.load({
      google: {
        families: [ 'Material+Icons' ]
      }
    });
  </script>`
