### ISSUE TITLE
Line-height difference between Mac and Windows

### ISSUE THREAD

**Issue by mlncstr** [typekit/webfontloader#381]
Our team is currently creating our own unique web font for branded icons and everything with webfontloader works fine except for the font ascent / descent (line-height). 

Using the same version of Chrome on both Mac and Windows, there's a 10px difference in the line-height between the icons. 

Anyone have any experience or ideas with how to fix this beside doing a JS check on the OS and serving a supplementary CSS file?

**Comment by shalanah** [comment]
This is most likely tied to your font metrics. There are Mac-specific and PC-specific metrics in your fonts and if they aren't aligned you can see differences in the browser based on OS. There are also more subtle issues in browser rendering but this usually not on the count of a 10px diff.

As an easy fix, Font squirrel has a generator that can help you align those font metrics (https://www.fontsquirrel.com/tools/webfont-generator). Make sure you click on "Expert" mode and under "Vertical metrics" make sure "Auto-Adjust" is selected.

You'll probably want to do a deep dive into OS/2 and hhea numbers.

**Comment by mlncstr** [comment]
@shalanah Thank you much! We'll look into it. I do know that we are dynamically creating the font files via webpack, so we may have to do a deeper dive here, but this certainly helps.

**Comment by markmakes** [comment]
Since this our fonts are compiled using your library, is there any way to set these metrics in the pre-compile settings?

**Comment by wappguru** [comment]
@shalanah thanks! Worked great.
