### ISSUE TITLE
Would this add Font Awesome 5 support? 

### ISSUE THREAD

**Issue by weilinzung** [typekit/webfontloader#391]
Would this add Font Awesome 5 support? 

https://fontawesome.com/get-started/web-fonts-with-css

https://use.fontawesome.com/releases/v5.0.6/css/all.css

**Comment by roboteight** [comment]
Try this out…
```
<link rel="preload" href="//use.fontawesome.com/releases/v5.0.8/css/all.css" as="style" crossorigin="crossorigin" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S">
<script>
	WebFontConfig = {
		google: {
			families: ['Montserrat:400,700', 'Roboto:400,700']
			},
		custom: {
			families: ['Font Awesome\ 5 Icons:400,900', 'Font Awesome\ 5 Brands:400'],
		        urls: ['//use.fontawesome.com/releases/v5.0.8/css/all.css']
		},
	timeout: 2000
};
</script>
```

**Comment by weilinzung** [comment]
do i have to include this as fallback ?

`<link rel="preload" href="//use.fontawesome.com/releases/v5.0.8/css/all.css" as="style" crossorigin="crossorigin" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S">`

thanks!

**Comment by roboteight** [comment]
You're welcome!

Oh, it's not a fallback - it preloads the stylesheet. You don't need to include it, but you can read up here if interested https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
