### ISSUE TITLE
wf-active/wf-inactive classes activated way too late as of lately

### ISSUE THREAD

**Issue by Krinkle** [typekit/webfontloader#45]
Hi,

On a site of mine I'm using webfont.js (loaded from [//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js](https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js).

I'm also using 

```
.wf-loading h1,
.wf-loading h2,
.wf-loading h3 {
    visibility: hidden; 
}
.wf-active h1 .wf-inactive h1,
.wf-active h2 .wf-inactive h2,
.wf-active h3, .wf-inactive h3 {
    visibility: visible;
}
```

To avoid FOUTs.

and in HTML:

```
    <script>
    window.WebFontConfig = {
      google: { families: ['Open+Sans:300,700,400', 'Allan:bold'] }
    };
    </script>
    <script src="//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js"></script>
```

However as of this week the headings are hidden for many seconds (up to 3-10 seconds). This is happening in both Chrome (Mac) and IE8 (Windows XP) for me.

When debugging in Chrome I can see that both the fonts are loaded, and the document-ready as well as the window-onload event have been fired long before the headings are appearing.

When I switched back to `1.0.21/webfont.js` everything was fine.

**Comment by bluthut11-ui** [comment]
Coment
